spring:
    mvc:
        hiddenmethod:
            filter:
                enabled: true
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop
    datasource:
        url: jdbc:h2:mem:db

api-gov:
    geo:
        base-url: https://geo.api.gouv.fr
        regions-url: /regions
